Fix undefined reference to `_imp___TrackMouseEvent@4' error.
Notice for CYGWIN we are not using the comdlg32 library but are using comctl32. Changing comdlg32 to comctl32 fixed the linker error I was receiving why trying to build the library using MinGW.

This change was tested in both Wine and a Windows 95 VM and I didn't receive any errors relating to functions defined in comdlg32 because it's not used.